### ISSUE TITLE
Code of the old results

### ISSUE THREAD

**Issue by AegeusZerium** [Python-simulation/Black-hole-simulation-using-python#1]
Hi, I saw your old results (images) and they turned to be the things that I was exactly looking for, can you please share the code you used to create these plots?

**Comment by marcelrsoub** [comment]
Invoking @Python-simulation for this discussion.

**Comment by Python-simulation** [comment]
I made some changes to the main file. Now it display trajectories without issues. I also add a old version into the old folder to display trajectories alone, but with Euler method...

**Comment by Python-simulation** [comment]
@AegeusZerium was it what you were looking for ?

**Comment by AegeusZerium** [comment]
@Python-simulation yes, thank you very much for the quick response and for the code, and thank you @marcelrsoub.
