### ISSUE TITLE
Not works anymore

### ISSUE THREAD

**Issue by alonsoir** [Python-simulation/Black-hole-simulation-using-python#4]
Hi i have just tried to run your code using Pillow 5.1, without luck 

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
pip install -r requirements.txt
Requirement already satisfied: numpy>=1.14 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: matplotlib>=3.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.7.1)
Requirement already satisfied: scipy>=1.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.11.1)
ERROR: Could not find a version that satisfies the requirement PIL>=5.1 (from versions: none)
ERROR: No matching distribution found for PIL>=5.1

I have Pillow 9.4.0, so do i have to downgrade?

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
pip install Pillow==5.1
Collecting Pillow==5.1
  Downloading Pillow-5.1.0.tar.gz (14.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... done
  Created wheel for Pillow: filename=Pillow-5.1.0-cp311-cp311-macosx_10_9_x86_64.whl size=462690 sha256=f2e4faf891e91b33565f6fad427b461b9beacabb822ad0e614d0ea450011b4c7
  Stored in directory: /Users/aironman/Library/Caches/pip/wheels/90/8f/90/401a3b33bdfc4ffc28443b3ec2d54766c682523e95e2693658
Successfully built Pillow
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.7.1 requires pillow>=6.2.0, but you have pillow 5.1.0 which is incompatible.
bokeh 3.2.1 requires pillow>=7.1.0, but you have pillow 5.1.0 which is incompatible.
scikit-image 0.20.0 requires pillow>=9.0.1, but you have pillow 5.1.0 which is incompatible.
imageio 2.31.1 requires pillow>=8.3.2, but you have pillow 5.1.0 which is incompatible.
Successfully installed Pillow-5.1.0

<▸> ~/g/Black-hole-simulation-using-python
└➤
pip install -r requirements.txt

Requirement already satisfied: numpy>=1.14 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: matplotlib>=3.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.7.1)
Requirement already satisfied: scipy>=1.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.11.1)
ERROR: Could not find a version that satisfies the requirement PIL>=5.1 (from versions: none)
ERROR: No matching distribution found for PIL>=5.1

┌<▪> ~/g/Black-hole-simulation-using-python
└➤
pip list | grep Pillow
Pillow                        5.1.0

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
python black_hole.py
Openning /Users/aironman/git/Black-hole-simulation-using-python/images/milkyway.jpg
Traceback (most recent call last):
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 1013, in <module>
    blackhole = BlackHole()
                ^^^^^^^^^^^
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 49, in __init__
    self.open(img_name, size=self.axe_X)
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 143, in open
    self.img_original = Image.open(img_name, mode='r')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/Image.py", line 2559, in open
    preinit()
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/Image.py", line 376, in preinit
    from . import JpegImagePlugin
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 41, in <module>
    from . import Image, ImageFile, TiffImagePlugin
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/TiffImagePlugin.py", line 400, in <module>
    class ImageFileDirectory_v2(collections.MutableMapping):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
pip uninstall Pillow
Found existing installation: Pillow 5.1.0
Uninstalling Pillow-5.1.0:
  Would remove:
    /usr/local/anaconda3/lib/python3.11/site-packages/Pillow-5.1.0.dist-info/*
Proceed (Y/n)? Y
  Successfully uninstalled Pillow-5.1.0

┌<▪> ~/g/Black-hole-simulation-using-python
└➤
pip install pillow
Collecting pillow
  Obtaining dependency information for pillow from https://files.pythonhosted.org/packages/07/22/93d6b5aa5917d09ec7088a2c4d1821848f3f95fbdc2633ba9d9fc28444a1/Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl.metadata
  Using cached Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl.metadata (9.5 kB)
Using cached Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl (3.5 MB)
Installing collected packages: pillow
Successfully installed pillow-10.1.0

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
python black_hole.py

Openning /Users/aironman/git/Black-hole-simulation-using-python/images/milkyway.jpg
Traceback (most recent call last):
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 1013, in <module>
    blackhole = BlackHole()
                ^^^^^^^^^^^
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 49, in __init__
    self.open(img_name, size=self.axe_X)
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 149, in open
    self.img_debut = self.img_resize(size)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 167, in img_resize
    self.img_debut = self.img_debut.resize((axe_X, axe_Y), Image.ANTIALIAS)
                                                           ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

So, i need Pillow >=5.1 but bellow 10.1.0...

**Comment by Python-simulation** [comment]
Hi ! I will look into it in more detail later, but a quick search reveals that pillow 10 removed the attribute ANTIALIAS: https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias
You can try Image.LANCZOS instead of Image.ANTIALIAS.

**Comment by alonsoir** [comment]
Do you think is necessary to change something to work with latest branch?

**Comment by Python-simulation** [comment]
I've just made the necessary change (replace Image.ANTIALIAS to Image.Resampling.LANCZOS). Tell me if it work for you now.

**Comment by alonsoir** [comment]
Hi, thanks for the changes, but i am afraid that it is not working for me. I pulled the changes, uninstalled pillow previous version, 10.0.1, installed pillow framework version as requirements.txt and failed.

┌<▪> ~/g/Black-hole-simulation-using-python
└➤
pip uninstall Pillow
Found existing installation: Pillow 10.0.1
Uninstalling Pillow-10.0.1:
  Would remove:
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/*
    /usr/local/anaconda3/lib/python3.11/site-packages/Pillow-10.0.1.dist-info/*
  Would not remove (might be manually added):
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libXau.6.0.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libbrotlicommon.1.1.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libbrotlidec.1.1.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libfreetype.6.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libharfbuzz.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/liblcms2.2.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/liblzma.5.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libopenjp2.2.5.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libpng16.16.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libsharpyuv.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libtiff.6.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libwebp.7.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libwebpdemux.2.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libwebpmux.3.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libxcb.1.1.0.dylib
    /usr/local/anaconda3/lib/python3.11/site-packages/PIL/.dylibs/libz.1.3.dylib
Proceed (Y/n)? Y
  Successfully uninstalled Pillow-10.0.1

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
pip install pillow==5.1
Collecting pillow==5.1
  Using cached Pillow-5.1.0-cp311-cp311-macosx_10_9_x86_64.whl
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 10.1.0
    Uninstalling Pillow-10.1.0:
      Successfully uninstalled Pillow-10.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.8.0 requires pillow>=6.2.0, but you have pillow 5.1.0 which is incompatible.
deepface 0.0.79 requires Pillow>=5.2.0, but you have pillow 5.1.0 which is incompatible.
scikit-image 0.20.0 requires networkx>=2.8, but you have networkx 2.6.3 which is incompatible.
scikit-image 0.20.0 requires pillow>=9.0.1, but you have pillow 5.1.0 which is incompatible.
imageio 2.31.4 requires pillow>=8.3.2, but you have pillow 5.1.0 which is incompatible.
bokeh 2.4.3 requires pillow>=7.1.0, but you have pillow 5.1.0 which is incompatible.
retina-face 0.0.13 requires Pillow>=5.2.0, but you have pillow 5.1.0 which is incompatible.
pytesseract 0.3.10 requires Pillow>=8.0.0, but you have pillow 5.1.0 which is incompatible.
Successfully installed pillow-5.1.0

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
python black_hole.py
Openning /Users/aironman/git/Black-hole-simulation-using-python/images/milkyway.jpg
Traceback (most recent call last):
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 1016, in <module>
    blackhole = BlackHole()
                ^^^^^^^^^^^
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 50, in __init__
    self.open(img_name, size=self.axe_X)
  File "/Users/aironman/git/Black-hole-simulation-using-python/black_hole.py", line 144, in open
    self.img_original = Image.open(img_name, mode='r')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/Image.py", line 2559, in open
    preinit()
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/Image.py", line 376, in preinit
    from . import JpegImagePlugin
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 41, in <module>
    from . import Image, ImageFile, TiffImagePlugin
  File "/usr/local/anaconda3/lib/python3.11/site-packages/PIL/TiffImagePlugin.py", line 400, in <module>
    class ImageFileDirectory_v2(collections.MutableMapping):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
pip install -r requirements.txt
Requirement already satisfied: numpy>=1.14 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.25.2)
Requirement already satisfied: matplotlib>=3.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.8.0)
Requirement already satisfied: scipy>=1.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.11.3)
ERROR: Could not find a version that satisfies the requirement PIL>=5.1 (from versions: none)
ERROR: No matching distribution found for PIL>=5.1

┌<▪> ~/g/Black-hole-simulation-using-python
└➤
pip install pillow
Collecting pillow
  Obtaining dependency information for pillow from https://files.pythonhosted.org/packages/07/22/93d6b5aa5917d09ec7088a2c4d1821848f3f95fbdc2633ba9d9fc28444a1/Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl.metadata
  Using cached Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl.metadata (9.5 kB)
Using cached Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl (3.5 MB)
Installing collected packages: pillow
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-image 0.20.0 requires networkx>=2.8, but you have networkx 2.6.3 which is incompatible.
Successfully installed pillow-10.1.0

┌<▸> ~/g/Black-hole-simulation-using-python
└➤
python black_hole.py
Openning /Users/aironman/git/Black-hole-simulation-using-python/images/milkyway.jpg
size 360x180 pixels

M = 4.1e+08 M☉	8.06e+38 Kg
Rs = 8 ua	1.20e+12 m
D = 50 ua	7.48e+12 m

alpha_min: 24.3 [24.2, 24.3]
last angle 155.7
trajectories time: 0.6

matrix creation estimation time: 0.1s
matrix created in time: 0.0 s

global computing time: 0.6

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication macOSVersion]: unrecognized selector sent to instance 0x7fc99d8aa5d0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8153f5fa6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff814eeb231 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff81549b2a4 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff815363893 ___forwarding___ + 1379
	4   CoreFoundation                      0x00007ff8153632a8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000000109ba8d02 GetRGBA + 50
	6   libtk8.6.dylib                      0x0000000109ba8bf4 TkpGetColor + 484
	7   libtk8.6.dylib                      0x0000000109ae0629 Tk_GetColor + 153
	8   libtk8.6.dylib                      0x0000000109acfc66 Tk_Get3DBorder + 134
	9   libtk8.6.dylib                      0x0000000109acfacf Tk_Alloc3DBorderFromObj + 127
	10  libtk8.6.dylib                      0x0000000109ae1b81 DoObjConfig + 1009
	11  libtk8.6.dylib                      0x0000000109ae1675 Tk_InitOptions + 357
	12  libtk8.6.dylib                      0x0000000109ae1555 Tk_InitOptions + 69
	13  libtk8.6.dylib                      0x0000000109b127d5 CreateFrame + 1605
	14  libtk8.6.dylib                      0x0000000109b12ab7 TkListCreateFrame + 151
	15  libtk8.6.dylib                      0x0000000109b0a5b8 Initialize + 2120
	16  _tkinter.cpython-311-darwin.so      0x00000001097276fb Tcl_AppInit + 91
	17  _tkinter.cpython-311-darwin.so      0x00000001097273e9 Tkapp_New + 585
	18  _tkinter.cpython-311-darwin.so      0x000000010972718e _tkinter_create_impl + 222
	19  _tkinter.cpython-311-darwin.so      0x0000000109726d96 _tkinter_create + 182
	20  python3.11                          0x0000000108eb0aad cfunction_vectorcall_FASTCALL + 93
	21  python3.11                          0x0000000108fa4ef7 _PyEval_EvalFrameDefault + 238407
	22  python3.11                          0x0000000108e4b89f _PyFunction_Vectorcall + 511
	23  python3.11                          0x0000000108e4df30 _PyObject_Call_Prepend + 192
	24  python3.11                          0x0000000108ee0777 slot_tp_init + 183
	25  python3.11                          0x0000000108ed469a type_call + 122
	26  python3.11                          0x0000000108fa5095 _PyEval_EvalFrameDefault + 238821
	27  python3.11                          0x0000000108e4b89f _PyFunction_Vectorcall + 511
	28  python3.11                          0x0000000108e4df30 _PyObject_Call_Prepend + 192
	29  python3.11                          0x0000000108ee0777 slot_tp_init + 183
	30  python3.11                          0x0000000108ed469a type_call + 122
	31  python3.11                          0x0000000108fa5095 _PyEval_EvalFrameDefault + 238821
	32  python3.11                          0x0000000108f6823d _PyEval_Vector + 493
	33  python3.11                          0x0000000108f67fda PyEval_EvalCode + 250
	34  python3.11                          0x0000000109019667 run_mod + 167
	35  python3.11                          0x0000000109019475 pyrun_file + 133
	36  python3.11                          0x0000000109018f53 _PyRun_SimpleFileObject + 275
	37  python3.11                          0x00000001090188ff _PyRun_AnyFileObject + 143
	38  python3.11                          0x000000010903d73b pymain_run_file_obj + 267
	39  python3.11                          0x000000010903d1b5 pymain_run_file + 85
	40  python3.11                          0x000000010903caa8 Py_RunMain + 1816
	41  python3.11                          0x0000000108dda1f8 main + 56
	42  dyld                                0x00007ff814f1f3a6 start + 1942
)
libc++abi: terminating due to uncaught exception of type NSException
[1]    7034 abort      python black_hole.py

**Comment by Python-simulation** [comment]
Thank you for your detailed traceback, it hellped me to find the problems. First problem solved is the wrong name 'PIL' in the requirements which should be 'pillow' since they changed the package name in pypi. Secondly, matplotlib doesn't take the correct backend when using a mac, see this [issue](https://github.com/matplotlib/matplotlib/issues/13414). I fixed it by forcing the matplotlib backend to Tkinter. Let me know if it finally works for you!

**Comment by alonsoir** [comment]
Awesome, thank you very much for update the code. It is soooo beatiful. I will try to learn from the code.
